### ISSUE TITLE
Crash when dismissing bulletin board

### ISSUE THREAD

**Issue by yusuftor** [alexisakers/BulletinBoard#188]
**Problem Description:**
I was running my iOS app in the simulator and I experienced a crash I think just after the bulletin board was hidden.

**Environment:**
 - Device: iPhone 11
 - OS: iOS 13.2.2 simulator
 - Version of BulletinBoard: 4.1.2

This is the crash report stack:

```
#0	0x000000010b96f85f in closure #5 in BLTNItemManager.refreshCurrentItemInterface(elementsChanged:) at /Users/MyApp/Pods/BulletinBoard/Sources/BLTNItemManager.swift:651
#1	0x000000010b963b8e in closure #1 in AnimationChain.performNextAnimation() [inlined] at /Users/MyApp/Pods/BulletinBoard/Sources/Support/Animations/AnimationChain.swift:91
#2	0x000000010b963b57 in partial apply for closure #1 in AnimationChain.performNextAnimation() ()
#3	0x000000010b962381 in thunk for @escaping @callee_guaranteed (@unowned Bool) -> () ()
#4	0x00007fff2574c976 in __NSFireDelayedPerform ()
#5	0x00007fff23bb2944 in __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ ()
#6	0x00007fff23bb2632 in __CFRunLoopDoTimer ()
#7	0x00007fff23bb1c8a in __CFRunLoopDoTimers ()
#8	0x00007fff23bac9fe in __CFRunLoopRun ()
#9	0x00007fff23babe16 in CFRunLoopRunSpecific ()
#10	0x00007fff38438bb0 in GSEventRunModal ()
#11	0x00007fff4784fb48 in UIApplicationMain ()
#12	0x00000001080e714b in main at /Users/.../MyApp/AppDelegate.swift:27
#13	0x00007fff51a1dc25 in start ()
#14	0x00007fff51a1dc25 in start ()
```

and this is the line where it crashed:

```
self.bulletinController.isDismissable = self.currentItem.isDismissable && (showActivityIndicator == false)
```

I can see that `showActivityIndicator` is false and `self.currentItem.isDismissable` is set to false.

Does anyone know what's causing this crash exactly?

**Comment by alexaubry** [comment]
Can you let me know if this is still an issue in the upcoming release? #189

**Comment by yusuftor** [comment]
@alexisakers Super late reply but I'm using version 5 now and I just ran into this issue again. However, I think it's a mistake on my part. I had the same function called twice in quick succession in my code by accident which resulted in the bulletin being presented and dismissed really quickly.

 For reference, it crashes on the line `self.bulletinController.contentStackView.alpha = contentAlpha`. But it does say "BLTNBoard was compiled with optimization - stepping may behave oddly; variables may not be available." so I don't know if that's the correct line or not.
